## Task:1

In [85]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
print(np.__version__, pd.__version__)

2.5.3 3.0.6

In [86]:
df=pd.read_csv('students.csv')
print(df)

   Stud_id  Age      Name  Gender                     Program  Semester  \
0     r001   21     Jawad    Male                        BSAI         1
1     r002   22     Nimra  Female                        BSAI         2
2     r003   23     Talha    Male  bs artificial intelligence         3
3     r004   24   Ibrahim    Male                        BSAI         4
4     r005   25   Khurram    Male                        BSAI         5
5     r006   26     Qasim    Male                        BSAI         6
6     r007   27       Ali    Male                       BSCYS         7
7     r008   28    Adeena  Female                        BSSE         8
8     r009   29     Ahmed    Male                        BSAI         1
9     r010   30    Zohaib    Male                        BSAI         2
10    r011   31  Muhammad    Male                        BSAI         3
11    r012   32      Noor     NaN                        BSAI         4
12    r013   33    Raheem    Male                        BSAI         5
13    r014   34      Rana    Male                        BSAI         6
14    r015   35    Jinnah    Male                        BSAI         7
15    r016   36      Zain    Male                        BSCS         8
16    r016   37      Asad    Male                        BSCS         1
17    r018   38     Tooba  Female                        BSAI         2
18    r019   39     Tariq    Male                        BSAI         3
19    r020   40      Taha    Male                        BSAI         4

         City  Attendance  Cgpa  Cred_hrs Passed
0   Wah Cantt         120  4.99        10    Yes
1   Islamabad         175  3.98        11    Yes
2   Islamabad          76  3.97        12     No
3   Islamabad          77  3.96        13    Yes
4   Islamabad          78  2.54        14    Yes
5   Islamabad          79  3.54        15    Yes
6      Lahore          80  3.99        16    Yes
7   Islamabad          81  3.98        17    Yes
8   Islamabad          82  3.97        18     No
9   Islamabad          83  3.96        10    Yes
10  Islamabad          84  2.54        11    Yes
11  Islamabad          30  3.54        12    Yes
12  Islamabad          86  3.99        13    Yes
13  Islamabad          87  3.98        14    Yes
14  Islamabad          88  3.97        15     No
15  Islamabad          89  3.96        16    Yes
16  Islamabad          90  2.54        17    Yes
17  Islamabad          91  3.54        18     No
18  Islamabad          92  3.09        15    Yes
19  Islamabad          93  2.89        16    Yes

In [24]:
print(df.head(5))

  Stud_id  Age     Name  Gender Program  Semester       City  Attendance  \
0    r001   21    Jawad    Male    BSAI         1  Wah Cantt         100
1    r002   22    Nimra  Female    BSAI         2  Islamabad          75
2    r003   23    Talha    Male    BSAI         3  Islamabad          76
3    r004   24  Ibrahim    Male    BSAI         4  Islamabad          77
4    r005   25  Khurram    Male    BSAI         5  Islamabad          78

   Cgpa  Cred_hrs Passed
0  3.99        10    Yes
1  3.98        11    Yes
2  3.97        12     No
3  3.96        13    Yes
4  2.54        14    Yes

In [5]:
print(df.tail(5))

   Stud_id  Age   Name  Gender Program  Semester       City  Attendance  Cgpa  \
15    r016   36   Zain    Male    BSCS         8  Islamabad          89  3.96
16    r017   37   Asad    Male    BSCS         1  Islamabad          90  2.54
17    r018   38  Tooba  Female    BSAI         2  Islamabad          91  3.54
18    r019   39  Tariq    Male    BSAI         3  Islamabad          92  3.09
19    r020   40   Taha    Male    BSAI         4  Islamabad          93  2.89

    Cred_hrs Passed
15        16    Yes
16        17    Yes
17        18     No
18        15    Yes
19        16    Yes

In [6]:
print(df.shape)

(20, 11)

In [6]:
print(df.columns)

Index(['Stud_id', 'Age', 'Name', 'Gender', 'Program', 'Semester', 'City',
       'Attendance', 'Cgpa', 'Cred_hrs', 'Passed'],
      dtype='str')

In [8]:
print(df.dtypes)

Stud_id           str
Age             int64
Name              str
Gender            str
Program           str
Semester        int64
City              str
Attendance      int64
Cgpa          float64
Cred_hrs        int64
Passed            str
dtype: object

In [9]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Stud_id     20 non-null     str
 1   Age         20 non-null     int64
 2   Name        20 non-null     str
 3   Gender      20 non-null     str
 4   Program     20 non-null     str
 5   Semester    20 non-null     int64
 6   City        20 non-null     str
 7   Attendance  20 non-null     int64
 8   Cgpa        20 non-null     float64
 9   Cred_hrs    20 non-null     int64
 10  Passed      20 non-null     str
dtypes: float64(1), int64(4), str(6)
memory usage: 1.8 KB
None

In [ ]:
print(df.describe())

            Age   Semester  Attendance       Cgpa   Cred_hrs
count  20.00000  20.000000   20.000000  20.000000  20.000000
mean   30.50000   4.100000   84.800000   3.596000  14.150000
std     5.91608   2.314713    6.542171   0.554146   2.560325
min    21.00000   1.000000   75.000000   2.540000  10.000000
25%    25.75000   2.000000   79.750000   3.427500  12.000000
50%    30.50000   4.000000   84.500000   3.960000  14.500000
75%    35.25000   6.000000   89.250000   3.980000  16.000000
max    40.00000   8.000000  100.000000   3.990000  18.000000

## Task:2

In [10]:
print(df[['Name','Program','Cgpa']])

        Name Program  Cgpa
0      Jawad    BSAI  3.99
1      Nimra    BSAI  3.98
2      Talha    BSAI  3.97
3    Ibrahim    BSAI  3.96
4    Khurram    BSAI  2.54
5      Qasim    BSAI  3.54
6        Ali   BSCYS  3.99
7     Adeena    BSSE  3.98
8      Ahmed    BSAI  3.97
9     Zohaib    BSAI  3.96
10  Muhammad    BSAI  2.54
11      Noor    BSAI  3.54
12    Raheem    BSAI  3.99
13      Rana    BSAI  3.98
14    Jinnah    BSAI  3.97
15      Zain    BSCS  3.96
16      Asad    BSCS  2.54
17     Tooba    BSAI  3.54
18     Tariq    BSAI  3.09
19      Taha    BSAI  2.89

In [25]:
df['Name']

0        Jawad
1        Nimra
2        Talha
3      Ibrahim
4      Khurram
5        Qasim
6          Ali
7       Adeena
8        Ahmed
9       Zohaib
10    Muhammad
11        Noor
12      Raheem
13        Rana
14      Jinnah
15        Zain
16        Asad
17       Tooba
18       Tariq
19        Taha
Name: Name, dtype: str

In [37]:
df[df['Cgpa']>4.0]

Empty DataFrame
Columns: [Stud_id, Age, Name, Gender, Program, Semester, City, Attendance, Cgpa, Cred_hrs, Passed]
Index: []

In [46]:
df[(df['Name']=='Nimra')|(df['City']=='Islamabad')]

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
1,r002,22,Nimra,Female,BSAI,2,Islamabad,75,3.98,11,Yes
2,r003,23,Talha,Male,BSAI,3,Islamabad,76,3.97,12,No
3,r004,24,Ibrahim,Male,BSAI,4,Islamabad,77,3.96,13,Yes
4,r005,25,Khurram,Male,BSAI,5,Islamabad,78,2.54,14,Yes
5,r006,26,Qasim,Male,BSAI,6,Islamabad,79,3.54,15,Yes
7,r008,28,Adeena,Female,BSSE,8,Islamabad,81,3.98,17,Yes
8,r009,29,Ahmed,Male,BSAI,1,Islamabad,82,3.97,18,No
9,r010,30,Zohaib,Male,BSAI,2,Islamabad,83,3.96,10,Yes
10,r011,31,Muhammad,Male,BSAI,3,Islamabad,84,2.54,11,Yes
11,r012,32,Noor,Female,BSAI,4,Islamabad,85,3.54,12,Yes
12,r013,33,Raheem,Male,BSAI,5,Islamabad,86,3.99,13,Yes
13,r014,34,Rana,Male,BSAI,6,Islamabad,87,3.98,14,Yes
14,r015,35,Jinnah,Male,BSAI,7,Islamabad,88,3.97,15,No
15,r016,36,Zain,Male,BSCS,8,Islamabad,89,3.96,16,Yes
16,r017,37,Asad,Male,BSCS,1,Islamabad,90,2.54,17,Yes
17,r018,38,Tooba,Female,BSAI,2,Islamabad,91,3.54,18,No
18,r019,39,Tariq,Male,BSAI,3,Islamabad,92,3.09,15,Yes
19,r020,40,Taha,Male,BSAI,4,Islamabad,93,2.89,16,Yes

In [47]:
df['Program'].value_counts()

Program
BSAI     16
BSCS      2
BSCYS     1
BSSE      1
Name: count, dtype: int64

In [48]:
df.isna().sum()

Stud_id       0
Age           0
Name          0
Gender        0
Program       0
Semester      0
City          0
Attendance    0
Cgpa          0
Cred_hrs      0
Passed        0
dtype: int64

In [49]:
df.isnull().sum()

Stud_id       0
Age           0
Name          0
Gender        0
Program       0
Semester      0
City          0
Attendance    0
Cgpa          0
Cred_hrs      0
Passed        0
dtype: int64

In [51]:
df[df['Program']=='BSAI']

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
0,r001,21,Jawad,Male,BSAI,1,Wah Cantt,100,3.99,10,Yes
1,r002,22,Nimra,Female,BSAI,2,Islamabad,75,3.98,11,Yes
2,r003,23,Talha,Male,BSAI,3,Islamabad,76,3.97,12,No
3,r004,24,Ibrahim,Male,BSAI,4,Islamabad,77,3.96,13,Yes
4,r005,25,Khurram,Male,BSAI,5,Islamabad,78,2.54,14,Yes
5,r006,26,Qasim,Male,BSAI,6,Islamabad,79,3.54,15,Yes
8,r009,29,Ahmed,Male,BSAI,1,Islamabad,82,3.97,18,No
9,r010,30,Zohaib,Male,BSAI,2,Islamabad,83,3.96,10,Yes
10,r011,31,Muhammad,Male,BSAI,3,Islamabad,84,2.54,11,Yes
11,r012,32,Noor,Female,BSAI,4,Islamabad,85,3.54,12,Yes
12,r013,33,Raheem,Male,BSAI,5,Islamabad,86,3.99,13,Yes
13,r014,34,Rana,Male,BSAI,6,Islamabad,87,3.98,14,Yes
14,r015,35,Jinnah,Male,BSAI,7,Islamabad,88,3.97,15,No
17,r018,38,Tooba,Female,BSAI,2,Islamabad,91,3.54,18,No
18,r019,39,Tariq,Male,BSAI,3,Islamabad,92,3.09,15,Yes
19,r020,40,Taha,Male,BSAI,4,Islamabad,93,2.89,16,Yes

In [52]:
df[df['Cgpa']>=3.5]

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
0,r001,21,Jawad,Male,BSAI,1,Wah Cantt,100,3.99,10,Yes
1,r002,22,Nimra,Female,BSAI,2,Islamabad,75,3.98,11,Yes
2,r003,23,Talha,Male,BSAI,3,Islamabad,76,3.97,12,No
3,r004,24,Ibrahim,Male,BSAI,4,Islamabad,77,3.96,13,Yes
5,r006,26,Qasim,Male,BSAI,6,Islamabad,79,3.54,15,Yes
6,r007,27,Ali,Male,BSCYS,7,Lahore,80,3.99,16,Yes
7,r008,28,Adeena,Female,BSSE,8,Islamabad,81,3.98,17,Yes
8,r009,29,Ahmed,Male,BSAI,1,Islamabad,82,3.97,18,No
9,r010,30,Zohaib,Male,BSAI,2,Islamabad,83,3.96,10,Yes
11,r012,32,Noor,Female,BSAI,4,Islamabad,85,3.54,12,Yes
12,r013,33,Raheem,Male,BSAI,5,Islamabad,86,3.99,13,Yes
13,r014,34,Rana,Male,BSAI,6,Islamabad,87,3.98,14,Yes
14,r015,35,Jinnah,Male,BSAI,7,Islamabad,88,3.97,15,No
15,r016,36,Zain,Male,BSCS,8,Islamabad,89,3.96,16,Yes
17,r018,38,Tooba,Female,BSAI,2,Islamabad,91,3.54,18,No

In [57]:
df[df['Attendance']<70]

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
11,r012,32,Noor,Female,BSAI,4,Islamabad,30,3.54,12,Yes

In [58]:
df['Program'].value_counts()

Program
BSAI     16
BSCS      2
BSCYS     1
BSSE      1
Name: count, dtype: int64

In [59]:
df['Cgpa'].mean()

np.float64(3.596)

In [60]:
df['Attendance'].mean()

np.float64(82.05)

## Task:3

In [70]:
df.isna().sum()
df.isnull().sum()

Stud_id       0
Age           0
Name          0
Gender        1
Program       0
Semester      0
City          0
Attendance    0
Cgpa          0
Cred_hrs      0
Passed        0
dtype: int64

In [71]:
df[df['Cgpa']>4]

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
0,r001,21,Jawad,Male,BSAI,1,Wah Cantt,100,4.99,10,Yes

In [75]:
df[df['Attendance']>100]

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
0,r001,21,Jawad,Male,BSAI,1,Wah Cantt,120,4.99,10,Yes
1,r002,22,Nimra,Female,BSAI,2,Islamabad,175,3.98,11,Yes

In [80]:
df[(df['Program']!='BSAI')&(df['Program']!='BSSE')&(df['Program']!='BSCS')&(df['Program']!='BSCYS')]

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
2,r003,23,Talha,Male,bs artificial intelligence,3,Islamabad,76,3.97,12,No

In [82]:
df['Stud_id'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19    False
Name: Stud_id, dtype: bool

## Task:4

In [95]:
df=pd.read_excel('students.xlsx')
df

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
0,r001,21,Jawad,Male,BSAI,1,Wah Cantt,100,3.99,10,Yes
1,r002,22,Nimra,Female,BSAI,2,Islamabad,75,3.98,11,Yes
2,r003,23,Talha,Male,BSAI,3,Islamabad,76,3.97,12,No
3,r004,24,Ibrahim,Male,BSAI,4,Islamabad,77,3.96,13,Yes
4,r005,25,Khurram,Male,BSAI,5,Islamabad,78,2.54,14,Yes
5,r006,26,Qasim,Male,BSAI,6,Islamabad,79,3.54,15,Yes
6,r007,27,Ali,Male,BSCYS,7,Lahore,80,3.99,16,Yes
7,r008,28,Adeena,Female,BSSE,8,Islamabad,81,3.98,17,Yes
8,r009,29,Ahmed,Male,BSAI,1,Islamabad,82,3.97,18,No
9,r010,30,Zohaib,Male,BSAI,2,Islamabad,83,3.96,10,Yes
10,r011,31,Muhammad,Male,BSAI,3,Islamabad,84,2.54,11,Yes
11,r012,32,Noor,Female,BSAI,4,Islamabad,85,3.54,12,Yes
12,r013,33,Raheem,Male,BSAI,5,Islamabad,86,3.99,13,Yes
13,r014,34,Rana,Male,BSAI,6,Islamabad,87,3.98,14,Yes
14,r015,35,Jinnah,Male,BSAI,7,Islamabad,88,3.97,15,No
15,r016,36,Zain,Male,BSCS,8,Islamabad,89,3.96,16,Yes
16,r017,37,Asad,Male,BSCS,1,Islamabad,90,2.54,17,Yes
17,r018,38,Tooba,Female,BSAI,2,Islamabad,91,3.54,18,No
18,r019,39,Tariq,Male,BSAI,3,Islamabad,92,3.09,15,Yes
19,r020,40,Taha,Male,BSAI,4,Islamabad,93,2.89,16,Yes

In [112]:
df = pd.read_json('students_fixed.json')
df

,Stud_id,Age,Name,Gender,Program,Semester,City,Attendance,Cgpa,Cred_hrs,Passed
0,r001,21,Jawad,Male,BSAI,1,Wah Cantt,100,3.99,10,Yes
1,r002,22,Nimra,Female,BSAI,2,Islamabad,75,3.98,11,Yes
2,r003,23,Talha,Male,BSAI,3,Islamabad,76,3.97,12,No
3,r004,24,Ibrahim,Male,BSAI,4,Islamabad,77,3.96,13,Yes
4,r005,25,Khurram,Male,BSAI,5,Islamabad,78,2.54,14,Yes
5,r006,26,Qasim,Male,BSAI,6,Islamabad,79,3.54,15,Yes
6,r007,27,Ali,Male,BSCYS,7,Lahore,80,3.99,16,Yes
7,r008,28,Adeena,Female,BSSE,8,Islamabad,81,3.98,17,Yes
8,r009,29,Ahmed,Male,BSAI,1,Islamabad,82,3.97,18,No
9,r010,30,Zohaib,Male,BSAI,2,Islamabad,83,3.96,10,Yes
10,r011,31,Muhammad,Male,BSAI,3,Islamabad,84,2.54,11,Yes
11,r012,32,Noor,Female,BSAI,4,Islamabad,85,3.54,12,Yes
12,r013,33,Raheem,Male,BSAI,5,Islamabad,86,3.99,13,Yes
13,r014,34,Rana,Male,BSAI,6,Islamabad,87,3.98,14,Yes
14,r015,35,Jinnah,Male,BSAI,7,Islamabad,88,3.97,15,No
15,r016,36,Zain,Male,BSCS,8,Islamabad,89,3.96,16,Yes
16,r017,37,Asad,Male,BSCS,1,Islamabad,90,2.54,17,Yes
17,r018,38,Tooba,Female,BSAI,2,Islamabad,91,3.54,18,No
18,r019,39,Tariq,Male,BSAI,3,Islamabad,92,3.09,15,Yes
19,r020,40,Taha,Male,BSAI,4,Islamabad,93,2.89,16,Yes

In [113]:
df['Cgpa']

0     3.99
1     3.98
2     3.97
3     3.96
4     2.54
5     3.54
6     3.99
7     3.98
8     3.97
9     3.96
10    2.54
11    3.54
12    3.99
13    3.98
14    3.97
15    3.96
16    2.54
17    3.54
18    3.09
19    2.89
Name: Cgpa, dtype: float64

In [115]:
df[['Cgpa']]

    Cgpa
0   3.99
1   3.98
2   3.97
3   3.96
4   2.54
5   3.54
6   3.99
7   3.98
8   3.97
9   3.96
10  2.54
11  3.54
12  3.99
13  3.98
14  3.97
15  3.96
16  2.54
17  3.54
18  3.09
19  2.89